displayName=Mortimer Calculator
author=Zachary Jacobson
description=Calculates which task Mortimer offers is best
tags=mortimer,calculator,morty,wyrmscraig,sailing,slayer
version=1.1
plugins=com.mortimercalculator.MortimerCalculatorPlugin
build=standard