displayName=MortimerCalculator
author=Zachary Jacobson
description=Calculates which task Mortimer offers is best
tags=mortimer,calculator,morty,wyrmscraig,sailing,slayer
version=1.0
plugins=com.mortimercalculator.MortimerCalculatorPlugin
build=standard